version: '2.1'
services:
  bot_app:
    build: .
    container_name: bot_app
    restart: always
    environment:
     - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - var_data:/var
    logging:
        options:
            max-size: 1m

volumes:
  var_data: